coverage:
  status:
    project:
      default:
        target: 90%

    patch:
      default:
        target: 95%

comment:
  layout: "header, diff, flags, components"

component_management:
  individual_components:
    - component_id: riverfit_generator
          name: riverfit_generator
          paths:
            - riverfit_generator/**
