name: riverfit_annotation
description: Annotation library for Riverfit.
version: 1.0.0
publish_to: none
environment:
  sdk: ">=2.18.0 <3.0.0"
  
dependencies:
  meta: ^1.15.0
  riverpod_annotation: ^2.6.0

dev_dependencies:
  build_runner: ^2.4.0
  coverage: ^1.11.0
  junitreport: ^2.0.0 
  mockito: ^5.4.0
  test: ^1.25.0
