name: riverfit_annotation
description: Annotation library for Riverfit.
version: 1.0.0
publish_to: none
environment:
  sdk: ">=2.18.0 <3.0.0"
  
dependencies:
  meta: ^1.15.0
  riverpod_annotation: ^2.6.0
