name: riverfit_generator
description: A code generation library that bridges the gap between riverpod_generator and retrofit_generator for Flutter projects.
version: 1.0.0
publish_to: none
homepage: https://github.com/digitaldem/riverfit
repository: https://github.com/digitaldem/riverfit
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.11.0
  build: ^2.4.0
  meta: ^1.15.0
  retrofit: ^4.4.0
  riverpod_annotation: ^2.6.0 
  riverpod_generator: ^2.6.0
  source_gen: ^1.5.0

  riverfit_annotation:
    path: ../riverfit_annotation

dev_dependencies:
  build_runner: ^2.4.0
  coverage: ^1.11.0
  junitreport: ^2.0.0 
  mockito: ^5.4.0
  test: ^1.25.0

topics:
  - code-generation
  - riverpod
  - retrofit
  - flutter
