name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  annotation:
    name: Riverfit Annotation
    uses: ./.github/workflows/dart.yml
    with:
      working-directory: riverfit_annotation

  generator:
    name: Riverfit Generator
    uses: ./.github/workflows/dart.yml
    with:
      working-directory: riverfit_generator
