name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  annotation:
    name: Riverfit Annotation
    uses: ./.github/workflows/dart.yml
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
    with:
      working-directory: riverfit_annotation

  generator:
    name: Riverfit Generator
    uses: ./.github/workflows/dart.yml
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
    with:
      working-directory: riverfit_generator
  